from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
import time
driver = webdriver.Chrome()
driver.get("http://practice.automationtesting.in/")
driver.find_element(By.LINK_TEXT, "My Account").click()
username = driver.find_element(By.ID, "username")
username.send_keys("tututur@mail.ru")
password = driver.find_element(By.ID, "password")
password.send_keys("123123.Uliya")
driver.find_element(By.CSS_SELECTOR, "[value='Login']").click()
driver.find_element(By.LINK_TEXT, "Shop").click()
driver.execute_script("window.scrollBy(0, 300);")
driver.find_element(By.CSS_SELECTOR, "[href='/shop/?add-to-cart=182']").click()
time.sleep(10)
driver.find_element(By.CLASS_NAME, "cartcontents").click()
time.sleep(7)
checkout = WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.CLASS_NAME, "checkout-button.button.alt.wc-forward")))
driver.find_element(By.CLASS_NAME, "checkout-button.button.alt.wc-forward").click()
first_name_chek = WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "[name='billing_first_name']")))
first_name = driver.find_element(By.CSS_SELECTOR, "[name='billing_first_name']")
first_name.send_keys("Yuliya")
last_name = driver.find_element(By.ID, "billing_last_name")
last_name.send_keys("Krupnitskaya")
phone = driver.find_element(By.ID, "billing_phone")
phone.send_keys("88002000600")
address = driver.find_element(By.ID, "billing_address_1")
address.send_keys("Pushkina")
city = driver.find_element(By.ID, "billing_city")
city.send_keys("Norilsk")
state = driver.find_element(By.ID, "billing_state")
state.send_keys("County")
postcode = driver.find_element(By.ID, "billing_postcode")
postcode.send_keys("663300")
country = driver.find_element(By.ID, "select2-chosen-1")
country_select = driver.find_element(By.CLASS_NAME, "select2-results")
driver.find_element(By.CSS_SELECTOR, "[value='RU']")
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(6)
driver.find_element(By.CSS_SELECTOR, "[for='payment_method_cheque']").click()
driver.find_element(By.CLASS_NAME, "button.alt").click()
element = WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.CLASS_NAME, "woocommerce-thankyou-order-received"), "Thank you. Your order has been received."))
check_payments = WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.CLASS_NAME, "method"), "Check Payments"))
driver.quit()

